### ISSUE TITLE
Plugins path?

### ISSUE THREAD

**Issue by bagong** [supercollider/sc-chocolatey#1]
Hi @kindohm ,

how do I have to read this line:

https://github.com/supercollider/sc-chocolatey/blob/master/sc3-plugins/tools/chocolateyinstall.ps1#L8

Does it mean, sc3-plugins get installed to

    %AppData%\Local\SuperColllider\Extensions\SC3-plugins\SC3-plugins

and

    %AppData%\Local\SuperColllider\Extensions\SC3-plugins\plugins

While I see the good intention to bundle the extensions in one folder, this is not good for the 32-bit version, which contains SuperNova. SuperNova expects all plugin-binaries to reside in a folder "plugins" which must be a *direct* subfolder of "Extensions" (or the Application-Folder). There must be nothing between "Extensions" and "plugins".  So the plugins-directory should actually be ...\Extensions. But maybe I misread, then please ignore. For the 64-bit version it doesn't matter, because scsynth does not have this limitation and we don't have a 64-bit supernova version yet. That will probably change in 3.9, btw.

**Comment by kindohm** [comment]
It sounds like I need to change the paths, and also account for differences between 32-bit and 64-bit.  I don't think I completely understand the requirements here though. Is there a document that explains exactly where/how to unzip and place the sc3-plugins files? It sounds like there are three possible locations:

- 64-bit installation
- 32-bit installation without SuperNova
- 32-bit installation with SuperNova

**Comment by bagong** [comment]
I think it's actually simpler than it looks, sorry for the complicated explanation. In both cases it should be fine to extract the zip directly into "Extensions". In the 32-bit case you will get Extensions\plugins and Extensions\SC3plugins, in the 64-bit case you will get just one folder, Extensions\SC3plugins. I am not sure how exact it is, but the Readme should actually contain the info I sketched.
As far as I see there is no 32-bit without supernova install? While there is a 32-bit build without supernova, I think you are not providing it, and that is fine. That second 32-bit build is only there for sonic-pi requirements.

https://github.com/supercollider/sc3-plugins/blob/master/README_WINDOWS.txt.in

**Comment by kindohm** [comment]
Ok, got it. I'll adjust the package install logic to account for this.

**Comment by kindohm** [comment]
Looking for clarification. Are these the correct paths where SC3Plugins should be unzipped/extracted:

- 64-bit: `C:\Users\<user>\AppData\Local\SuperCollider\Extensions\SC3Plugins`
- 32-bit with supernova: `C:\Users\<user>\AppData\Local\SuperCollider\Extensions\plugins`

I'm not familiar with the 32-bit version and supernova. It seems odd to me that the contents of the SC3Plugins archive would just unzip to the `\plugins` folder, where other things might exist.

**Comment by bagong** [comment]
If you extract the 32-bit zip-archive, it will create two folders, the plugins one you reproduced *and* a folder `C:\Users\<user>\AppData\Local\SuperCollider\Extensions\SC3plugins`. The plugins folder contains only the binary plugins, the SC3plugins folder contains all the rest, classes, help-files, readme's and other stuff. This is in fact somewhat confusing, but SuperNova has the plugins folder hardcoded and will only look in a folder `plugins` within the Extensions folder. There is nothing we can do for now, except somebody has an idea. Fortunately Windows by default merges folders with the same name, so in the unlikely case that a plugins folder folder already exists, or if somebody copies a plugins-folder to that location later, the contents would be added if no direct name conflicts exist.

You can experiment with this: Execute `Server.supernova`, then `Server.boot`and observe what happens with different path-names.

**Comment by kindohm** [comment]
ah, got it. I never looked in the 32-bit sc3-plugins archive to check its contents. Yes, both the 64-bit and 32-bit archives will be extracted to `\Extensions`, so the `SC3Plugins` and `plugins` folders will be created in the correct locations: `\Extensions\SC3Plugins` and `\Extensions\plugins`.

**Comment by bagong** [comment]
*p*lugins :smile:
